In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
#存矩阵，存在当前文件夹
torch.save(x,'x-file')
x2=torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [4]:
#存张量列表
y=torch.zeros(4)
torch.save([x,y],'x-files')
x2,y2=torch.load('x-files')
x2,y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [5]:
#写入或者读取从字符串映射到张量的字典
mydict={'x':x,'y':y}
torch.save(mydict,'mydict')
mydict2=torch.load('mydict')
mydict2


{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [6]:
#加载和保存模型参数
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden=nn.Linear(20,256)
        self.output=nn.Linear(256,10)
    def forward(self,x):
        return self.output(F.relu(self.hidden(x)))

net=MLP()
X=torch.randn(size=(2,20))
Y=net(X)


In [7]:
#将模型的参数存储为一个叫做mlp.params的文件
torch.save(net.state_dict(),'mlp.params')


In [9]:
#加载参数
clone=MLP()
clone.load_state_dict(torch.load('mlp.params'))#load_state_dict函数只会将参数值加载到模型的参数字典中
clone.eval()#切换到评估模式，这样就不会计算梯度
Y_clone=clone(X)
Y_clone==Y


tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])