In [1]:
import torch
from torch import nn
import torch.nn.functional as F

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x - x.mean()

In [2]:
layer = CenteredLayer()
a=layer(torch.FloatTensor([1, 2, 3, 4, 5]))
print(a)

tensor([-2., -1.,  0.,  1.,  2.])


In [3]:
net= nn.Sequential(nn.Linear(8, 128), CenteredLayer())
y = net(torch.rand(4, 8))
y.mean()

tensor(-3.2596e-09, grad_fn=<MeanBackward0>)

In [12]:
#带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))#nn.Parameter的作用是将weight声明为模型参数，torch.randn(in_units, units)是weight的初始值
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, x):
        linear = torch.matmul(x, self.weight.data) + self.bias.data
        return F.relu(linear)#F.relu()是一个自带的激活函数
dense = MyLinear(5, 3)
print(dense.weight)

Parameter containing:
tensor([[-0.8655,  0.9956,  1.2987],
        [-0.6606,  0.1571,  0.9605],
        [ 0.3680, -1.1694, -0.2845],
        [ 1.1310, -1.5770, -1.0799],
        [-0.0745,  0.2627, -1.4953]], requires_grad=True)


tensor([[ 0.9956,  1.2987],
        [ 0.1571,  0.9605],
        [-1.1694, -0.2845],
        [-1.5770, -1.0799],
        [ 0.2627, -1.4953]], grad_fn=<IndexBackward0>)

In [13]:
dense(torch.rand(2, 5))

tensor([[0.0000, 0.6156, 2.2124],
        [0.0000, 0.6074, 2.3466]])

In [14]:
#使用自定义层构建模型
net=nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[25.0188],
        [21.7443]])