In [1]:
import torch

In [3]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape
X=x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
X
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
Y
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)



(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [10]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a

tensor([[0],
        [1],
        [2]])

In [11]:
b


tensor([[0, 1]])

In [12]:
a+b


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [14]:
X


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
X[-1]
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
X[0:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])