In [4]:
import torch



In [5]:
x=torch.arange(4.0)
x


tensor([0., 1., 2., 3.])

In [6]:
x.requires_grad_(True)
x.grad


In [7]:
y=2*torch.dot(x,x)
y


tensor(28., grad_fn=<MulBackward0>)

In [8]:
y.backward()
x.grad


tensor([ 0.,  4.,  8., 12.])

In [9]:
x.grad==4*x


tensor([True, True, True, True])

In [11]:
# x.grad.zero_()
y=x.sum()
y.backward()
x.grad


tensor([2., 2., 2., 2.])

In [15]:
x.grad.zero_()
y=x*x
y.sum()

tensor(14., grad_fn=<SumBackward0>)

In [16]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [14]:
y.sum().backward()
x.grad


tensor([0., 2., 4., 6.])

In [17]:
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x
z.sum().backward()
x.grad==u


tensor([True, True, True, True])

In [19]:
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c


a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()

In [20]:
a.grad==d/a

tensor(True)