In [1]:
import torch
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y, x*y, x/y, x**y


(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [2]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
len(x)


4

In [6]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
A.T


tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
B==B.T

In [10]:
torch.arange(24).reshape(2,3,4)



tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [13]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
A,B
# print(id(A),id(B))

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [16]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [15]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [17]:
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [22]:
A=torch.arange(40,dtype=torch.float32).reshape(2,5,4)
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [23]:
A.sum()

tensor(780.)

In [ ]:
A_sum_axis0=A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

In [25]:
A_sum_axis0=A.sum(axis=1)
A_sum_axis0,A_sum_axis0.shape


(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [26]:
A_sum_axis0=A.sum(axis=2)
A_sum_axis0,A_sum_axis0.shape


(tensor([[  6.,  22.,  38.,  54.,  70.],
         [ 86., 102., 118., 134., 150.]]),
 torch.Size([2, 5]))

In [27]:
A.sum(axis=[0,1])

tensor([180., 190., 200., 210.])

In [28]:
A.sum(axis=[0,2])


tensor([ 92., 124., 156., 188., 220.])

In [29]:
A.mean(),A.sum()/A.numel()


(tensor(19.5000), tensor(19.5000))

In [30]:
sum_A=A.sum(axis=1,keepdims=True)
sum_A


tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

In [31]:
A/sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [32]:
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [34]:
x

tensor([0., 1., 2., 3.])

In [35]:
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)


(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))